channels:
- conda-forge
dependencies:
- python=3.11.0
- pip<=22.3
- pip:
  - mlflow==3.1.4
  - cloudpickle==3.1.1
  - numpy==2.0.0
  - pandas==2.2.2
  - psutil==7.0.0
  - scikit-learn==1.7.0
  - scipy==1.16.0
  - typing==3.7.4.3
name: mlflow-env
